
help: Configuration file, two robots, three targets, two type II zones
testID: 104
exp: "simulation"  # 0: "simulation", 1: "ros simulation", 2: "ros real"
steps: 50
solver: "All" # "RiskAware" or "RiskNeutral" or "Dist" or "All"
frame_id: "world"

Problem:
    robotID: [0, 1]
    robotID_drone: [3, 4]
    targetID: [0, 1, 2, 3]
    targetID_car: [3, 4]
    targetStartPos: [[-1.5, 0.6], [-1.5, 0.3], [-1.5, -0.3], [-1.5, -0.6]] #, [1.5, 0.25]]  # [x, y], or [x, y, z]
    targetStartVel: [[0.1, 0.000], [0.1, 0.0], [0.1, 0.0], [0.1, -0.00]] #, [-0.1, 0]]
    robotStartPos: [[-2, 0.8], [-2, -0.8]] #, [2.0, 0.2]]
    robotStartVel: [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0]] #, [0, 0]]
    target_dyn_type: "second_order_dynamics"
    robot_dyn_type: "first_order_dynamics" # "second_order_dynamics"
    task_assignment_matrix: [[1, 1, 0, 0], 
                             [0, 0, 1, 1]] # [0, 0, 1]]  # robot i is assigned to target j
    target_movement: "linear"  # "random_walk" or "linear"
    # row is robot, column is target

    N : 2
    dt: 0.1
    dim: 2
    u_bounds: [-0.5, 0.5]  # control effort bounds
    x_bounds: [[-2.2, 2.2], [-2.2, 2.2]]  # x bound, and y bound
    weights : [0.05, 10.0, 100.0, 100.0] # control input, trace, slack 1, slack 2  # it's variables that you can change 
    range_sensor: [15.0, 0.2]   #[range_peak, range_shape]
    bearing_sensor: [15.0, 0.2]   #[bearing_peak, bearing_shape]
    min_dist: 0.4
    max_dist: 1000  # can also affect the quality of the solution, can set inf
    solver_name: "resilient"
    resources: 500 # for each robot
    use_cent_solver: True # if True, the central solver will be used

    ## archived
    resources: 500 # for each robot


Zones:
    nTypeI: 0
    nTypeII: 2
    typeI_mu: [[0.0, 0.0], [-4, -3],  [2, 3]] # [x, y], or [x, y, z]     [[x1, y1], [x2, y2]]
    typeI_cov: [[0.5, 0.5], [0.6, 0.6], [0.2, 0.2]]
    typeII_mu: [[-0.3, 0.0], [1.0, 0.2]]
    typeII_cov: [[0.3, 0.3], [0.2, 0.2]]
    typeI_delta: [0.1, 0.1, 0.1]  # this is for the type I zones
    typeII_delta: [0.1, 0.1]  # this is for the type II zones
    eps1: 0.05
    eps2: 0.9
    eps2_single: 0.1

    #### attack parameters
    attack_recover_eps: 0.2
    attack_dt: 1 # every 1.0 second the attack will happen
    attack_mcnt: 1000 # the maximum number of attacks
    attack_seed: 0
